sudo: required
dist: trusty
language: php
php:
- '7.1'
- '7.2'
- nightly
before_install:
- composer config --global github-oauth.github.com $GITHUB_TOKEN
before_script: composer install
notifications:
  email:
    recipients:
    - alabard@gmail.com
    on_success: change
    on_failure: change
env:
  global:
    secure: NPmPNUmMuxBj9xHcXLFUf3KxPUMlXgcuZeVM3IaV4/lCBd4GXQ5wVTKBb7N7v90EDijLvNXsIQ0sSDnVAkteTi+O0sJUcAG1DKJMKIDU2HYd2llM+hbo2Nhfpm/jTOuZg6VTqFLKK1wUVFXPtHyX6sbbJRDCstDdLIb10noDnk5iaTP2LtDKd2lMcCjsymP1d+sqCwwREwKj/TIGqoFdkUTKbxy2MgQrV8kT+WwXAhq5l2x7MaQMOO2zcN+qI3T9yYyLyuB0DYnxv+U1AByQQoSG37rEySy6orZNDuN9BOMNFak2knbO0RUWuLnR3/Vj4VLDZx617ONNJ29PUgXRuzeDg51KBMo6BMT+PKUJdBx6710hOx3clgr3CRHJ/HzTcU4JiY6LRvxUsegLd0J2oGU7KBrVBbswSi5xY/NIhDp8dpRlKbmslDrg4kJgd5bbuyNOWsM5irGyYIi8R2oYzNJBQAKAQEjyjI2T/m0u+g8gGAlTr4fjWRkCBgz0ufnJu1tdnXeJ5K6XxP+NqvpXMHv+kehL4ElWAm3CHSLyeQBruzX2qfL3Ik4vAI5/RWeqoJGcPaB2vxELulcexqLkegXg+tOnXedKEvrVaT1l5SejdbPyO57PKL3t/H8ru3dpInS4muqD3EcZ/2eZB1puPEE/+bJWmNMqHAYfOW2mMwc=
