sudo: required
dist: trusty
language: php
php:
- '7.1'
- '7.2'
- nightly
before_install:
- composer config --global github-oauth.github.com "$GITHUB_TOKEN"
before_script: composer install
notifications:
  email:
    recipients:
    - alabard@gmail.com
    on_success: change
    on_failure: change
env:
  global:
    secure: kHeVqdlF1FW3enXwEhlJUF0I2sY7RWCkBD5QS/vLrO4b/nITVUvSsSbqTUIK11jejms15nk16Jk7lHiEsEnvNcye/ROgLRfvcrEJ4Vq2ZUp90mh1m1zqBzBBnz6xASdGF5IMbFzdYovHRBLKcGkmwj+HiPToFmin2Pn8quINYZxkB9KAYKFN3ISfgUD5K6KF1ARlZgjQqL5ppgkMCPOq8VCiFuhuL+q1OiTGkP8XfGDLlyCHYOe5NsG/yRAb6/zSH5jor+6sAawmXlOLcA1rXe/a5TjOZOvfOvtNYrZukVxArVDt7Ra8Oj7mKVozFwkFTvIWOAF1aHO7+KLDzrOWKSemgtvMBdQDrJCwRQxOajj178I0AS0JIT+uze4NBWIfLe+AGF4XhaW8XxFwTaf0czqMB29FPC8zt0i611tj+1PO/vkoAcFYH0aOgkZShmjvR9EPUvDJT9DuORO9zRPShcyrHbuYem7fqlH94kIFXeFRvezCXVcKokAQjf7ZcLCJfn9lNaxeWCBpX+Qqr6Fk20LLZtBFrhDU+VVD5/cMyWM8kVDdY/4zWDwVj+TWzr6f9waB6fcNn0oGtSvVigv/5CAf73nao1FPRPQ509wns0YaFpdJd0RXEpxbtZwMNWohLvjxCxm91fNBQS3Im5GFdpxHt9awHbaEurFSTz0xc+A=
